beer_shop_B/beer_shop/beer_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import main.views
import cart.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^item/(?P<item_id>\d+)', main.views.item, name='Сылки товаров'),
    url(r'^(?P<cat_id>\d+)', main.views.get_category, name='Сылки категорий'),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^$', main.views.home, name='home'),
    #url(r'^sidebar/', include('sidebar.urls')),
    #url(r'^auth/', include('loginsys.urls')),
    #url(r'^', include('article.urls')),
]

beer_shop_B/beer_shop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

beer_shop_B/beer_shop/cart/models.py
from django.db import models

beer_shop_B/beer_shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

beer_shop_B/beer_shop/cart/views.py
#from cart.models import order, all_order 
from main.models import Item,Category
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.decorators.http import require_POST
from django.contrib import auth
from .cart import Cart
from .forms import CartAddProductForm


# ------------------------------------------------------------------------------------------------

def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id = product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    if product and (not form.is_valid()):
        cart.add(product=product, quantity=1)
        return redirect('/')  
    return redirect('cart:CartDetail')    
    
    
def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id = product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')
    


    
def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'detail.html', {'cart': cart , 'username': auth.get_user(request).username})
    
# ------------------------------------------------------------------------------------------------   
 

beer_shop_B/beer_shop/cart/templates/detail.html
{% extends "index.html" %}

{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content_items %}
<div class='row'>
  <h1>Ваша корзина товаров</h1>
  <table class="table table-striped table-hover ">
    <thead>
      <tr class="info">
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="/item/{{ product.id }}/">
                <img src="{{ product.image }}" width="40px" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td><form action="{% url "cart:CartAdd" product.id %}" method="post" class="add" class="form">
    {{ item.update_quantity_form.quantity }}
    {{ item.update_quantity_form.update }}
    {% csrf_token %}
    <input class="btn btn-info" type="submit" value="Обновить">
</form></td>
            <td><a href="{% url 'cart:CartRemove' product.id %}" class="btn btn-info">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="info warning">
          <td>Итог</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="/" class="btn btn-info">Продолжить Шопинг</a>
    <a href="/order/create/" class="btn btn-info">Оформить заказ</a>
  </p>
  </div>
{% endblock %}